site_name: 化区生存指南
site_description: 面向化区同学的学习、科研与生活 Wiki
site_url: https://nku-chembug.github.io/

repo_url: https://github.com/nku-chembug/nku-chembug.github.io
repo_name: nku-chembug/nku-chembug.github.io
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.code.copy

  palette:
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式

    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式

plugins:
  - search:
      lang:
        - zh
        - en

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - 首页: index.md