nav:
  - 概览: index.md
  - 化学学院的学生组织: chem-organizations
  - 校级学生组织: school-organization
  - 怎样“水课”: easy-courses.md
  - 学生工作和正常生活的平衡: work-life-balance.md
  - 怎么做推送: social-media-posts.md
  - 怎么拍照: photography.md
  - 志愿时长去哪里水: volunteer-hours.md
